package com.sandao.entity;

import java.util.Date;

public class SimpleUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_user.user_id
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_user.user_name
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_user.password
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_user.create_date
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_user.email
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simple_user.user_id
     *
     * @return the value of simple_user.user_id
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simple_user.user_id
     *
     * @param userId the value for simple_user.user_id
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simple_user.user_name
     *
     * @return the value of simple_user.user_name
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simple_user.user_name
     *
     * @param userName the value for simple_user.user_name
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simple_user.password
     *
     * @return the value of simple_user.password
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simple_user.password
     *
     * @param password the value for simple_user.password
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simple_user.create_date
     *
     * @return the value of simple_user.create_date
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simple_user.create_date
     *
     * @param createDate the value for simple_user.create_date
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simple_user.email
     *
     * @return the value of simple_user.email
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simple_user.email
     *
     * @param email the value for simple_user.email
     *
     * @mbg.generated Tue Nov 21 15:40:10 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    @Override
    public String toString() {
        return "SimpleUser{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", password='" + password + '\'' +
                ", createDate=" + createDate +
                ", email='" + email + '\'' +
                '}';
    }
}